version: '3'

networks:
  binance-bot:
    name: binance-bot
    ipam:
      driver: default
      config:
        - subnet: "172.31.0.0/16"
          gateway: "172.31.0.1"


services:
  app:
    image: binance-bot:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: binance-bot
    restart: always
    networks:
      - binance-bot
